name: mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with mypy
      run: |
        python -m mypy src/pydw/game.py --strict --ignore-missing-imports
