name: Publish to Docker

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          username: justinbeetle
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: justinbeetle/publish-packages/game
          tag_with_sha: true
